Jm 45 microservice call whit session mail error
janis-commerce/mail pull request #2
Opened 2020-01-28 17:13 UTC by manuelvilche

Ticket: [JM-45](https://fizzmod.atlassian.net/browse/JM-45)
Descripción: se exporto la clase `Mail-error.js` para poder validar los errores y a su vez se agrego la posibilidad de enviar tanto un `body` con un email (to), o un `templateCode` solamente

2020-01-28 19:35 UTC, gastonpereyra commented on README.md
> +
* Para mi tanto acá, como en el ejemplo que sigue faltaría aclarar bien que no son métodos de clase sino de instancia.

* Y falta el `await` ya que `send` es `async`

Algo asi: 
```js
const mail = new Mail()

await mail.setBody('client-code').send();
```

2020-01-28 21:33 UTC, gastonpereyra approved these changes

2020-01-31 17:09 UTC, jormaechea requested changes

2020-01-31 17:09 UTC, jormaechea commented on lib/mail-validator.js
> +			throw new MailError('Empty field: to property is required when templateCode is not setted', MailError.codes.REQUIRED_FIELD_MISSING);
```suggestion
			throw new MailError('Empty field: to property is required when templateCode is not set', MailError.codes.REQUIRED_FIELD_MISSING);
```

2020-01-31 17:09 UTC, jormaechea commented on lib/mail-validator.js
> +			throw new MailError('Empty field: subject property is required when templateCode is not setted', MailError.codes.REQUIRED_FIELD_MISSING);
```suggestion
			throw new MailError('Empty field: subject property is required when templateCode is not set', MailError.codes.REQUIRED_FIELD_MISSING);
```

2020-01-31 17:09 UTC, jormaechea commented on lib/mail.js
> +		if(this.session)
```suggestion
cons ms = this.session ? this.session.getSessionInstance(MicroserviceCall) : new MicroserviceCall();`
```

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +const { Mail, MailError } = require('./../lib/index');
```suggestion
const { Mail, MailError } = require('../lib');
```

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +			it('Should throw when the values templateCode or body are missing', () => {
```suggestion
			it('Should throw when the values templateCode and body are missing', () => {
```

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +			it('Should throw when the value to is missing and body is setted', () => {
Por todos lados donde diga `setted`, es `set`

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +			it('Should throw when the value \'clientCode\' are not a string', () => {
```suggestion
			it('Should throw when the value of \'clientCode\' is not a string', () => {
```

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +			it('Should throw when the value \'body\' are not a string', () => {
```suggestion
			it('Should throw when the value of \'body\' is not a string', () => {
```

2020-01-31 17:09 UTC, jormaechea commented on tests/mail-test.js
> +				const mailData = mail.setTo('info@fizzmod.com')
Este `mailData` es algo raro.. Porque incluso no es ninguna data de mail, sino que es una promise, y en ningún lado se está awaiteando... Raros estos tests. Una forma más correcta de hacerlo es esta:

```js
await assert.rejects(() => mail
	.setTo(...)
	.setTemplateCode(...)
	.send(), microserviceCallError);
```

Básicamente lo que hacés es:
- Llamar a `assert.rejects` que recibe dos argumentos: un callback (que tiene que devolver una promise que es la que va a esperar), y opcionalmente el error que estás esperando que rejectee.
- `assert.rejects` devuelve una promise, por eso tenés que awaitearlo.

2020-01-31 21:33 UTC, jormaechea approved these changes

2020-01-31 21:33 UTC, merged